import os


AMQP_URI = os.environ["AMQP_URI"]
MONGO_URI = os.environ["MONGO_URI"]
HASOFFERS_NETWORK_TOKEN = ""
HASOFFERS_NETWORK_ID = ""
MIN_APPROVAL_ID = 0
PAGE_SIZE = 10
PROXIES = None
SENDGRID_API_KEY = ""
