import os


AMQP_URI = os.environ["CLOUDAMQP_URL"]
MONGO_URI = os.environ["MONGODB_URI"]
HASSOFFERS_NETWORK_TOKEN = os.environ["HASSOFFERS_NETWORK_TOKEN"]
HASSOFFERS_NETWORK_ID = os.environ["HASSOFFERS_NETWORK_ID"]
